GET http://localhost:3001/api/blogs

###

GET http://localhost:3001/api/blogs/663e41e47ce0081ebc18a8c8

###

DELETE http://localhost:3001/api/blogs/663e41e47ce0081ebc18a8c8

###

POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQwYzJlNjdmZDIxYWZjMTIxMDE0MDMiLCJpYXQiOjE3MTU1NDk1MzJ9.qDvzWq-TCEU_Z3n1whWnFsNadDAWCGPTSMHv-zg866s

{
    "title": "112test with user",
    "author": "213",
    "url": "213",
    "userId": "663ff3c63c2b7a4d803ece5f"
}

###

PUT http://localhost:3001/api/blogs/664c2668ba7180679984ee55
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQxMWEwMzA2NmMyYTBlYzNlYWVjZGIiLCJpYXQiOjE3MTYyNjU0ODIsImV4cCI6MTcxNjI2OTA4Mn0.yM2f_6NvNyI1C8oHImS8MxA8YQ2AdIX-qecTjxbTFyk

{
    "title": "my blog",
    "author": "asdfasd",
    "url": "asdf",
    "likes": 2
}