GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/6637b0ce9a6c106a66b9d69f

###

DELETE http://localhost:3001/api/notes/4

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "test123",
    "important": false,
    "userId": "663ff3c63c2b7a4d803ece5f"
}

###

PUT http://localhost:3001/api/notes/6637b0ce9a6c106a66b9d69f
Content-Type: application/json

{
    "content": "tsdf",
    "important": false
}