GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/6637edf00aee7f8a79805325

###

DELETE http://localhost:3001/api/persons/6637ee6dec64435a35a0efad

###

POST http://localhost:3001/api/persons
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2NjQwYzJlNjdmZDIxYWZjMTIxMDE0MDMiLCJpYXQiOjE3MTU1NDk1MzJ9.qDvzWq-TCEU_Z3n1whWnFsNadDAWCGPTSMHv-zg866s

{
    "name": "asd21312",
    "phone": "21-1231232133",
    "userId": "663ff3c63c2b7a4d803ece5f"
}

###

PUT http://localhost:3001/api/persons/6637edf00aee7f8a79805325
Content-Type: application/json

{
    "name": "Вадим",
    "phone": "21-2312349"
}