GET http://localhost:3001/api/notes

###

GET http://localhost:3001/api/notes/6

###

DELETE http://localhost:3001/api/notes/6

###

POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "test123",
    "important": false
}